config/routes.rb
Rails.application.routes.draw do
  resources :bus_operators 

  post 'bus_operators/:id/qualify', as: "qualify_bus_operator", to: "bus_operators#qualify", controller: 'bus_operators'
  get 'bus_operators/:id/qualifications', as: "qualifications_bus_operator", to: "bus_operators#qualifications", controller: 'bus_operators'  


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus_operator.rb
class BusOperator
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  field :average_rating, type: Float, default: 0
  field :description, type: String
  field :qualifications, type: Array, default: []
  field :qualification, type: Integer
  field :qualification_comment, type: String 
  
  def set_average_rating
      _average = 0    
      self.qualifications.each do |qualif|
        _average = _average + qualif[:qualification].to_f
      end      
      self.average_rating = (_average.to_f / self.qualifications.size).round(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bus_operators_controller.rb
class BusOperatorsController < ApplicationController  
  before_action :set_bus_operator, only: [:show, :edit, :update, :destroy,:qualify, :qualifications]  
  # GET /bus_operators
  # GET /bus_operators.json
  def index           
    #Perform Bus Operators update  
    RecorridoService.new.call
    if bus_operator_params[:criteria]
      @bus_operators = BusOperator.all.order_by(bus_operator_params[:criteria].to_sym => 'desc').page(params[:page].to_i).per(20)
    else
      @bus_operators = BusOperator.all.page(params[:page].to_i).per(20)
    end 
  end

  # GET /bus_operators/1
  # GET /bus_operators/1.json
  def show
  end

  # GET /bus_operators/new
  def new
    @bus_operator = BusOperator.new
  end

  # GET /bus_operators/1/edit
  def edit
  end

  # POST /bus_operators
  # POST /bus_operators.json
  def create
    @bus_operator = BusOperator.new(bus_operator_params)

    respond_to do |format|
      if @bus_operator.save
        format.html { redirect_to @bus_operator, notice: 'Bus operator was successfully created.' }
        format.json { render :show, status: :created, location: @bus_operator }
      else
        format.html { render :new }
        format.json { render json: @bus_operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bus_operators/1
  # PATCH/PUT /bus_operators/1.json
  def update
    respond_to do |format|
      if @bus_operator.update(bus_operator_params)
        format.html { redirect_to @bus_operator, notice: 'Bus operator was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus_operator }
      else
        format.html { render :edit }
        format.json { render json: @bus_operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bus_operators/1
  # DELETE /bus_operators/1.json
  def destroy
    @bus_operator.destroy
    respond_to do |format|
      format.html { redirect_to bus_operators_url, notice: 'Bus operator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /bus_operators/1/qualify
  # Add a new qualification for BusOperator
  def qualify    
    @bus_operator.push(qualifications: {qualification_comment: bus_operator_params[:qualification_comment], qualification: bus_operator_params[:qualification]})
    @bus_operator.set_average_rating
    @bus_operator.save!
    redirect_to qualifications_bus_operator_url
  end

  # GET /bus_operators/1/qualifications
  # Add a complete list of qualifications for BusOperator
  def qualifications
    @qualifications = Kaminari.paginate_array(@bus_operator.qualifications).page(params[:page]).per(20)    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus_operator
      @bus_operator = BusOperator.find(params[:id].to_i)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_operator_params
      params.fetch(:bus_operator, {}).permit(:description, :qualification_comment, :qualification, :criteria)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bus_operators_helper.rb
module BusOperatorsHelper
end

app/views/bus_operators/_form.haml
= form_with(model: bus_operator, local: true) do |form|
  - if bus_operator.errors.any?
    %div#error_explanation
      %h2= pluralize(bus_operator.errors.count, "error") + " prohibited this bus_operator from being saved:"
      %ul
      - bus_operator.errors.full_messages.each do |message|
        %li= message

  %div.form-group
    = label :description, "Descripción"
    %br
    = text_area(:bus_operator, :description, cols: 80, rows: 10)

  %div.actions
    = submit_tag 'Grabar', class: 'btn btn-primary'

app/views/bus_operators/edit.haml
%br
%h3
  Editando
  %small.text-muted= @bus_operator.official_name


= render 'form', bus_operator: @bus_operator

= link_to 'Ver ' + @bus_operator.official_name, @bus_operator
= link_to 'Listado', bus_operators_path

app/views/bus_operators/index.haml
%p#notice= notice

%h3 Operadores de buses

= form_tag bus_operators_url, :method => :get do          
  %div.form_group.col-3= select :bus_operator,:criteria, options_for_select([["Nombre", "official_name"], ["Calificacion", "average_rating"]]), {:prompt => 'Ordernar por'}, { class: 'form-control', onchange: 'this.form.submit();' }

%table.table.table-bordered.table-hover
  %thead.thead-dark
    %tr
      %th.span1 Logo
      %th.span1 Nombre
      %th.span1 Calificación
      %th.span1{:colspan => "3"} Opciones

  %tbody#operatorsTable
    - @bus_operators.each do |bus_operator|
      %tr
        %td= image_tag bus_operator.icons[:medium], class: 'rounded'
        %td= bus_operator.official_name
        %td{:class => "center"}
          = image_tag "star.min.svg"
          %br
          %span.badge.badge-pill.badge-secondary= bus_operator.average_rating.to_s + " de 5.0"
        %td= link_to 'Ver <span class="oi" data-glyph="pencil"></span>'.html_safe, bus_operator
        %td= link_to 'Editar', edit_bus_operator_path(bus_operator)

= paginate @bus_operators

app/views/bus_operators/new.haml
%h3 New Bus Operator

= render 'form', bus_operator: @bus_operator
= link_to 'Back', bus_operators_path

app/views/bus_operators/qualifications.haml
%br
%h4= "Calificaciones de " + @bus_operator.official_name
= link_to 'Volver', @bus_operator

%table.table.table-sm.table-bordered.table-hover
  %thead.thead-dark
    %tr
      %th.span1 #
      %th.span1 Nota
      %th.span1 Comentario      

  %tbody
    - @qualifications.each_with_index do |qual, idx|
      %tr
        %td= (idx + 1).to_s
        %td= qual[:qualification]
        %td= qual[:qualification_comment]        

= paginate @qualifications

app/views/bus_operators/show.haml
%br
%div.row
  %div.col-sm    
    - if notice
      %div.alert.alert-success= notice

%div.row
  %div.col-sm 
    %p.h4 
      = @bus_operator.official_name

    = link_to 'Editar', edit_bus_operator_path(@bus_operator) | 
    = link_to 'Ver calificaciones', qualifications_bus_operator_url

    %ul
      %li
        %p.h5
          Calificación
          = @bus_operator.average_rating.to_s + ' de 5'

      %li
        %p.h5
          Descripción:
          
        %p.lead= @bus_operator.description 

  %div.col-sm   
    = image_tag(@bus_operator.images[:mdpi])


%div.row
  %div.col-12

    = form_with model: @bus_operator, url: qualify_bus_operator_path, method: :post do
      
      %div.form_group{:style => "float:left"}
        = label :qualification_comment, 'Calificar'         
        %br
        = text_area(:bus_operator, :qualification_comment, cols: 80, rows: 10)
      
        = select :bus_operator,:qualification, options_for_select((1..5).to_a), {:prompt => 'Nota'}, { class: 'form-control'}
     
      %div.form_group
        %div.actions
          = link_to 'Volver',  bus_operators_path, class: 'btn btn-light'
          = submit_tag 'Grabar', class: 'btn btn-primary'
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recorridos Final Lap</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag '/assets/logo.png' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <p class="navbar-brand" ><img src="/assets/logo.png" style="width:50px"/></p>
      <p class="navbar-brand" ><i>Gustavo Castillo</i></p>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>